### ISSUE TITLE
Symbol’s function definition is void: request

### ISSUE THREAD

**Issue by greenonion** [dakrone/es-mode#42]
Hello, thanks for the great work on this package!

When I'm trying to execute a query I'm getting:
```
es--execute-region: Symbol’s function definition is void: request
```
on the minibuffer. I guess this is probably [this](https://github.com/dakrone/es-mode/blob/e72bc4c3ee731aef972a8bd2d324e6c032bffc94/es-mode.el#L586) line and related to https://github.com/dakrone/es-mode/pull/41

Running `package-list-packages` lists the `request` package as a `dependency` of es-mode, so I guess I have it installed. This is on OS X by the way. Let me know if I can do anything more to help.

**Comment by dakrone** [comment]
Whoops sorry! I pushed a commit that should fix it, can you give it a try?

**Comment by greenonion** [comment]
Yep, it works now! Thanks a lot, I'm a bit embarrassed it was that simple, I should have provided a PR :)

**Comment by dakrone** [comment]
Thanks for reporting it! :)

**Comment by greenonion** [comment]
Hey I think you forgot to merge the commit to the master branch :)

**Comment by ljos** [comment]
Should be OK now.

**Comment by greenonion** [comment]
Cheers!

**Comment by dakrone** [comment]
Whoops! Thanks @ljos!
